spring :
  datasource:
    url: jdbc:mysql://localhost:3307/Employee_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa :
    show-sql: true
    hibernate :
      ddl-auto : update